# Basic settings
log_dir: "log/alignment"
strategy: "deepspeed"

# Data configuration
data_cfg:
  target: src.data.data_interface.BaseDataInterface
  params:
    cfg:
      dataset: src.data.dataset.CslDailyDataset
      train_split: 'dataset/csl-daily/train.json'
      val_split: 'dataset/csl-daily/val.json'
      test_split: 'dataset/csl-daily/val.json'
      opt: 
        annotation_path: 'data/csl-daily/sentence_label/csl2020ct_v2.pkl'
        max_length: 256
        modalities:  
          use_features: false
          use_pred_pose: true
          use_gt_pose: true
          use_raw_pose: false
        pose_config:  
          pose_dir: "pred_poses_0521"
          norm_pose: true
      num_workers: 4

# Model configuration
model_cfg:
  target: src.model.alignment.AlignmentTrainer
  params:
    cfg:
      # Encoder weights path
      encoder_weights: "weights/hand_pose_encoder_from_wavellm_mt5_daily_pose_0521_v1.bin"
      
      # Training configuration
      training:
        batch_size: 32
        learning_rate: 1.0e-4
        weight_decay: 1.0e-4