# Basic settings
log_dir: 'log/omnihand'
strategy: 'ddp'

# Data configuration
data_cfg:
  target: src.data.data_interface.BaseDataInterface
  params:
    cfg: 
      dataset: src.data.dataset.SingleFrameDataset
      train_split: 'dataset/csl-news-200/train.json'
      val_split: 'dataset/csl-news-200/val.json'
      test_split: 'dataset/csl-news-200/val.json'
      opt: 
        load_feature: false
        norm_pose: true
      num_workers: 4

# Model configuration
model_cfg:
  target: src.model.omnihand.OmniHand
  params:
    cfg:
      learnable_weights: true
      backbone: 
        target: src.model.encoder.cubenet.CubeNet
        params: 
          input_dim: 32
          hidden_dims: [64, 128, 256, 512]
          num_blocks: [3, 4, 6, 3]
          strides: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 1, 1]] 
          block: src.model.encoder.cubenet.BasicBlock3D
          norm_layer: torch.nn.GroupNorm
        pretrained: weights/cubenet-base
        freeze: false
      discriminator:
        pretrained: null
        freeze: false
      training:
        use_discriminator: true
        disc_lr: 1.0e-6
        lambda_gan: 1.0
        lr: 1.0e-4
        betas: [0.9, 0.999]
        weight_decay: 0.01
