# Basic settings
log_dir: "log/peft_finetune"
strategy: "deepspeed"

# Data configuration
data_cfg:
  target: src.data.data_interface.BaseDataInterface
  params:
    cfg:
      dataset: src.data.dataset.CslNewsDataset
      train_split: 'dataset/csl-news-100/train.json'
      val_split: 'dataset/csl-news-100/val.json'
      test_split: 'dataset/csl-news-100/val.json'
      opt: 
        caption_path: "dataset/CSL_News_Labels_converted.json"
        max_length: 256
        modalities:  # Control which modalities to use
          use_features: true
          use_pred_pose: true
          use_raw_pose: false
        feature_config:  # Feature modality specific settings
          feature_dim: 512
          feature_dir: "features"
        pose_config:  # Pose modality specific settings
          pose_dir: "pred_poses"
      num_workers: 4

# Model configuration
model_cfg:
  target: src.model.trainer.WaveLLMTrainer
  params:
    cfg:
      # LLM configuration
      model_type: "mt5"
      model:
        model_path: "huggingface/mt5-pretrained"
        model_max_length: 2048
        
      # PEFT configuration
      use_peft: false
      fix_llm: false
      
      # Training configuration
      training:
        learning_rate: 3.0e-4
        weight_decay: 1.0e-4
        warmup_steps: 100
      